---
  - name: '### APPLY CONFIGURATION ###'
    hosts: all
    connection: local
    gather_facts: no
    # vars_prompt:
    #   - name: prompt_username
    #     prompt: "Please enter your username"
    #   - name: prompt_password
    #     prompt: "Please enter your password"
    #     private: yes
    tasks:

      ######################################################
      ##### pre_tasks
      ######################################################
      - name: enable netconf service on port 830
        junos_netconf:
          listens_on: 830
          state: present
          provider:
            host: "{{ ansible_host }}"
            username: "jcluser"
            password: "Juniper!1"
            # ssh_keyfile: "/root/.ssh/id_rsa.pub"

      - name: create new user account
        junos_user:
          name: ansible
          role: super-user
          sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
          state: present
          provider:
            host: "{{ ansible_host }}"
            username: "jcluser"
            password: "Juniper!1"
            # ssh_keyfile: "/root/.ssh/id_rsa.pub"
            port: 22

      - name: delete default interface configs and protocols stanza
        junos_config:
          lines:
            - delete protocols
            - wildcard range delete interfaces xe-0/0/[0-4]
            - delete interfaces lt-0/0/0
            - delete interfaces lo0
            - delete logical-systems
            - delete routing-instances
            - delete routing-options dynamic-tunnels
          comment: update config
          provider:
            host: "{{ ansible_host }}"
            username: "ansible"
            ssh_keyfile: "/root/.ssh/id_rsa.pub"
            port: 22


      ######################################################
      ##### Jinja2 configuration
      ######################################################
      - name: apply config
        junos_config:
          src: "{{ configuration }}"
          provider:
            host: "{{ ansible_host }}"
            username: "ansible"
            ssh_keyfile: "/root/.ssh/id_rsa.pub"
            port: 22

      ######################################################
      ##### MOTD Banner
      ######################################################
      - name: configure the login banner
        junos_banner:
          banner: login
          text: |
            ********************************* WARNING *********************************
            *                                                                         *
            * This system is for authorized users only. This, and any other sessions, *
            * can and will be monitored to determine whether or not it is being used  *
            * by an authorized user.                                                  *
            *                                                                         *
            * By logging into this system, you are consenting to such monitoring, and *
            * are advised that the system administrators retain the right to use any  *
            * recorded session as evidence of criminal activity, if such activity is  *
            * monitored.                                                              *
            *                                                                         *
            ********************************* WARNING *********************************
          state: present
          provider:
            host: "{{ ansible_host }}"
            username: "ansible"
            ssh_keyfile: "/root/.ssh/id_rsa.pub"
