snmp:
  name: "{{ inventory_hostname }}"
  location: '"Juniper vLabs"'
  contact: packetferret
  community:
    - string: 'vlabs'
      authorization: read-write
      clients:
        - 10.30.0.0/16
        - 10.20.0.0/16
  trapOptions:
    - source-address "{{ ansible_host }}"
  trapGroup:
    - name: TRAP-QUEEN
      version: v2
      port: 162
      categories:
        - chassis
        - routing
        - authentication
        - link
        - startup
        - services
      targets:
        - 10.30.2.1
